name: luminina
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf4ee'
    - '#f7a2b5'
    - '#000000'
    - '#5d68aa'
    - '#333e54'
  brandStrength: 0.9130201812367886
  lightness: 1
  saturation: 0.05852188915014267
  rhythmicContrast: 0.27188978530466557
purpose: []
