name: luminina
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf4ee'
    - '#f7a2b5'
    - '#000000'
    - '#5d68aa'
    - '#333e54'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
